var car = 'subaru';
console.log("Is car == 'subaru'? i pridict true.");
console.log(car == 'subaru');
console.log("Is car == 'toyota? i pridict false.");
console.log(car == 'toyota');
console.log("Is car == 'subaru'? i pridict true.");
console.log(car == 'subaru');
console.log("Is car == 'farari'? i pridict false.");
console.log(car == 'farari');
console.log("Is car == 'subaru'? i pridict true.");
console.log(car == 'subaru');
console.log("Is car == 'lexus' i pridict false.");
console.log(car == 'lexus');
console.log("Is car == 'subaru'? i pridict true.");
console.log(car == 'subaru');
console.log("Is car == 'mercedes' i pridict false.");
console.log(car == 'mercedes');
console.log("Is car == 'subaru'? i pridict true.");
console.log(car == 'subaru');
console.log("Is car == 'bugatti' i pridict false.");
console.log(car == 'bugatti');
